name: Build Nuitka Project

on:
  push:
    branches:
      - main  # 监听 main 分支上的 push 事件

jobs:
  build:
    runs-on: ubuntu-latest  # 选择使用 Ubuntu 操作系统

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout 当前仓库的代码

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # 配置 Python 版本
          architecture: 'x64'

      - name: Install Requirements
        run: |
            pip install -r requirements.txt
      

      - name: Run Nuitka build with app.py
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: app.py
          mode: onefile
          nuitka-version: main
          
